[features]
seeds = false
skip-lint = false
[programs.localnet]
movie_review_program = "EvyMLMUiSLkBPtuG94vbMViADdKHwKgoc4iwrJqv5Baq"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/Users/juan/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
